/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
 exports.seed = async function(knex) {
    // Deletes ALL existing entries
    await knex('rooms').del()
  
    await knex('rooms').insert([
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
        { name: "girlblock",phone_num:"123456789",category :"family",bio: "lsipdjei dnirnuenfr wdkijnernfw fioieurbfnn defdo,mbkjbkjbkbkjvkucycgvfgvjh h hjnih j fijrwhjr vwrjh jhwr vhwrh viuenrf",location: "443 greene ave",url: "https://photos.spareroom.com/images/flatshare/listings/unmodified/20/67/206733971.jpg?width=800&height=800&fit=bounds&auto=webp&optimize=medium",type_of: "room",quantity: "2",userid: "2"},
    ]
      
  
  );
  };
  